server:
  port: ${PORT:9090}  # Valor por defecto si PORT no está configurado
  url: ${SERVER_URL:http://localhost:9090}  # Valor por defecto si SERVER_URL no está configurado

spring:
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=Visons;encrypt=true;trustServerCertificate=true}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:Admin12345!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html # Ruta para acceder a Swagger UI: http://localhost:9090/swagger-ui.html